---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-fedora-latest
    image: fedora:latest
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: fedora-latest
