---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-ubuntu-devel
    image: ubuntu:devel
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: ubuntu-devel
