---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
driver:
  name: docker
platforms:
  - name: "bootstrap-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
verifier:
  name: ansible
