---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "bootstrap-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
