---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bootstrap-archlinux
    image: base/archlinux
  - name: bootstrap-alpine-3.6
    image: alpine:3.6
  - name: bootstrap-alpine-3.7
    image: alpine:3.7
  - name: bootstrap-centos-6
    image: centos:6
  - name: bootstrap-centos-7
    image: centos:7
  - name: bootstrap-debian-buster
    image: debian:buster
  - name: bootstrap-debian-jessie
    image: debian:jessie
  - name: bootstrap-debian-sid
    image: debian:sid
  - name: bootstrap-debian-stretch
    image: debian:stretch
  - name: bootstrap-debian-wheezy
    image: debian:wheezy
  - name: bootstrap-fedora-27
    image: fedora:27
  - name: bootstrap-fedora-28
    image: fedora:28
  - name: bootstrap-opensuse-42.2
    image: opensuse:42.2
  - name: bootstrap-opensuse-42.3
    image: opensuse:42.3
  - name: bootstrap-ubuntu-bionix
    image: ubuntu:bionic
  - name: bootstrap-ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
