---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-alpine-latest
    image: alpine:latest
    pre_build_image: yes
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: alpine-latest
