---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-fedora-rawhide
    image: fedora:rawhide
    registry:
      url: registry.fedoraproject.org
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: fedora-rawhide
