---
#
# Ansible managed
#

name: Release to Ansible Galaxy

on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
